name: 🐛 Баг
description: Отчет об ошибке
title: "🐛 "
labels:
  - bug
assignees:
  - 5yxar
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Баг
  - type: dropdown
    id: project-selector
    attributes:
      label: Проект
      options:
        - Первый проект
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Шаги воспроизведения
      placeholder: Список шагов воспроизведения ошибки
    validations:
      required: true
  - type: textarea
    id: required-behaviour
    attributes:
      label: Ожидаемое поведение
      placeholder: Каким образом система должна функционировать
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      placeholder: Прочая информация