name: 🚀 Новая функциональность
description: Запрос на добавление новой функциональности или на изменение уже существующей
title: "🚀 "
labels:
  - feature
assignees:
  - 5yxar
body:
  - type: markdown
    attributes:
      value: |
        # 🚀 Фича
  - type: dropdown
    attributes:
      label: Проект
      options:
        - Первый проект
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Что требуется реализовать
      placeholder: Общее описание новой функциональности
    validations:
      required: true
  - type: textarea
    id: technical-details
    attributes:
      label: Технические подробности реализации
      placeholder: Прочие технические детали аспектов реализации