name: Check-in

env:
  NETCORE_VERSION: '5.0.x'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  check_in:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout  
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --verbosity normal --no-restore
